name: Unit Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.4

      - name: Run deno test
        run: deno test src/
